wandb_version: 1

config:
  desc: null
  value: /home/zhuhe/HPE-with-Diffusion/config/sanitycheck_val.json
phase:
  desc: null
  value: val
gpu_ids:
  desc: null
  value: '1'
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689051321.169547
    t:
      1:
      - 1
      - 51
      - 55
      2:
      - 1
      - 41
      - 51
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.16
      5: 0.15.4
      8:
      - 5
